#!/bin/sh
# /etc/init.d/hbbtvproxy

### BEGIN INIT INFO
# Provides:          hbbtvproxy
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Redirects all traffic on port 80 to the HbbTV proxy
# Description:       Redirects all traffic on port 80 to the HbbTV proxy
### END INIT INFO


case "$1" in
  start)
    echo "Set IPTABLES"
    # run application you want to start
    sudo iptables -t nat -A POSTROUTING ! -d 192.168.0.1 -j MASQUERADE
    sudo iptables -t nat -A PREROUTING -i eth1 ! -d 192.168.0.1 -p tcp --dport 80 -j REDIRECT --to-port 8080
    echo "done"
;;
  stop)
    echo "REMOVE IPTABLES"
    # kill application you want to stop
    sudo iptables -t nat -D POSTROUTING ! -d 192.168.0.1 -j MASQUERADE
    sudo iptables -t nat -D PREROUTING -i eth1 ! -d 192.168.0.1 -p tcp --dport 80 -j REDIRECT --to-port 8080
    echo "done"
;;
  *)
    echo "Usage: /etc/init.d/hbbtvproxy {start|stop}"
    exit 1
    ;;
esac

exit 0
